#! /bin/bash

# cealkkadep
# This is a shell script for analysing Northern S‡mi sentences.
# It gives the analysis, but not the number of the rules used to disambiguate
# It uses the vislcg3 parser.

# This if-then-else business is here since victorio is picky as to what
# lookup it accepts.


if [ `hostname` == 'victorio.uit.no' ]
then
    LOOKUP=/opt/sami/xerox/c-fsm/ix86-linux2.6-gcc3.4/bin/lookup
else
    LOOKUP=`which lookup`
fi

while [ 1 ]                                 # as long as there is input
do                                          # run the following loop
echo -n "Atte cealkaga (ctrl-C = STOP): "          # (message to user)
read sentence                               # next 3 lines is the usual command
echo $sentence | \
preprocess --abbr=$GTHOME/gt/sme/bin/abbr.txt | \
$LOOKUP -flags mbTT -utf8 $GTHOME/gt/sme/bin/sme.fst | \
$GTHOME/gt/script/lookup2cg | \
vislcg3 --grammar $GTHOME/gt/sme/src/sme-dis.rle  | \
vislcg3 --grammar $GTHOME/gt/sme/src/sme-dep.rle  # source
#vislcg3 --grammar $GTHOME/gt/sme/bin/sme-dis.bin | \ 
#vislcg3 --grammar $GTHOME/gt/sme/src/sme-grc.rle # binary

done                      
exit 0

