#!/bin/bash
#
# Shell script for exporting cgi-scripts from cvs 
# to the official cgi-bin directory
# Only the cgi-scripts with tag "release" are exported.
# The command for tagging the release:    cvs tag release files...
#
# $Id$

EXPORTDIR="/opt/sami/www/cgi-bin/smi"
#EXPORTDIR="koe"
MODULE="gt/script/cgi-scripts"

### Export all the cgi-scripts
sudo rm -rf $EXPORTDIR/*.cgi
echo "**** Exporting module $MODULE to directory: $EXPORTDIR"
sudo cvs -d /usr/local/cvs/repository export -r release -d $EXPORTDIR $MODULE
sudo chmod 755 $EXPORTDIR/*

## Copy the language files to the official location

tmpdir="/usr/tmp"
optdir="/opt/smi/common/bin"
xdocsdir="xtdoc/gtuit/src/documentation/content/xdocs/cgi"

cd $tmpdir && cvs -d /usr/local/cvs/repository checkout xtdoc

langs="eng nno sme"
for lang in $langs
  do
  echo "cp $tmpdir/$xdocsdir/cgi-$lang.xml $optdir/"
  cp $tmpdir/$xdocsdir/cgi-$lang.xml $optdir/
done

