#! /bin/bash

# dep
# This is a shell script for analysing Northern Sámi sentences and giving
# them a dependency analysis.
# It gives the analysis, but not the number of the rules used to disambiguate
# It uses the vislcg3 parser.

while [ 1 ]                                 # as long as there is input
do                                          # run the following loop
echo -n "Atte cealkaga (ctrl-C = STOP): "          # (message to user)
read sentence                               # next 3 lines is the usual command
echo $sentence | preprocess --abbr=~/gt/sme/bin/abbr.txt | \
lookup -flags mbTT -utf8 ~/gt/sme/bin/sme.fst | ~/gt/script/lookup2cg | \
vislcg3 -g $HOME/gt/sme/src/sme-3dis.rle -C UTF-8 2>/dev/null | \
vislcg3 -g $HOME/gt/sme/src/sme-dep.rle -C UTF-8  2>/dev/null 


done                      
exit 0
