#! /bin/bash
# Script for analysing files.

dis ()
{
#echo -n "Entering dis $0"
#read sentence                               # next 3 lines is the usual command
cat $1 | ~/gt/script/preprocess --abbr=~/gt/sme/bin/abbr.txt | \
lookup -flags mbTT -utf8 ~/gt/sme/bin/sme.fst | ~/gt/script/lookup2cg | \
vislcg --grammar ~/gt/sme/src/sme-dis.rle --minimal
}
dis $1




