#! /bin/bash
# Script for analysing files.

dis ()
{
# echo -n "Entering dis $0"
# read sentence
# next 3 lines is the usual command
cat $1 | $GTHOME/gt/script/preprocess --abbr=$GTHOME/gt/sme/bin/abbr.txt | \
lookup -flags mbTT -utf8 $GTHOME/gt/sme/bin/sme.fst | \
$GTHOME/gt/script/lookup2cg | \
vislcg --grammar $GTHOME/gt/sme/src/sme-dis.rle --minimal
}
dis $1




