#!/bin/bash
#
# $Id$
# Shell script for exporting divvun.no and giellaktekno www-pages from cvs 
# to the official www-directory
#
# To get cvs ssh working without password prompting:
# ssh-keygen -t rsa
# <just type enter to all questions>
# chmod 0644 .ssh/id_rsa.pub
# scp id_rsa.pub <user>@cochise.uit.no:.ssh/authorized_keys2


CVS_RSH=ssh
MAIL_TO="borre.gaup@samediggi.no"
# This function uses cvs to checkout the directory given as it's argument,
# or updates the given directory.

checkout()
{
    REPOSITORY=":ext:cochise.uit.no:/usr/local/cvs/repository"
    TEMPDIR=$1
    echo "Checking out $TEMPDIR ..."
    cd
    if  ! [ -x $TEMPDIR ]; then
        cvs -d $REPOSITORY co $TEMPDIR 2> /dev/null
        if [ "$?" != "0" ]; then
            (echo "From: borre.gaup@samediggi.no"
            echo "Subject: cvs checkout error"
            echo "TO:$MAIL_TO"
            echo "")|sendmail -t
            # No point in continuing without any data to work on ...
            exit 1
        fi
    else
        cd $TEMPDIR
        cvs -z4 up -dP  2> /dev/null
        if [ "$?" != "0" ]; then
            (echo "From: borre.gaup@samediggi.no"
            echo "Subject: cvs update error"
            echo "TO:$MAIL_TO"
            echo "")|sendmail -t
            # No point in continuing without new data to work on ...
            exit 1
        fi
        cd
    fi
}

# This function uses the 'checkout' function to update or checkout
# the two directories used in the giellatekno and divvun sites.
# It also makes a symbolic link to gt/doc in the gtuit and sd sites, 
# making complete 'forrest-trees' out of both xtdoc/sd and xtdoc/gtuit

fetch_giella_and_divvun()
{
    for CVS_DIR in xtdoc gt/doc
    do
        checkout $CVS_DIR
    done

    for SITE in gtuit sd
    do
        cd $HOME/gt
        cp -a doc $HOME/xtdoc/$SITE/src/documentation/content/xdocs/.
        if [ "$?" != "0" ]; then
            (echo "From: borre.gaup@samediggi.no"
            echo "Subject: ln -s error"
            echo "TO:$MAIL_TO"
            echo "")|sendmail -t
            #  If this fails, then the common documentations won't be 
            #  updated ... quit script
            exit 1
        fi
    done
}

# This function validates the documents in the xtdoc/sd and xtdoc/gt 
# directories.
# If successfull it copies the relevant files to the tomcat-servers 
# directories, else it sends an e-mail to the site administrator.

validate_sites()
{
    ERROR_FILE="$HOME/forrest-validation-error.txt"
    for SITE in sd gtuit
    do
        cd $HOME/xtdoc/$SITE

        # Validate the docs, redirect error output to the ERROR_FILE
        echo "Validating docs in $SITE ..."
        forrest validate-xdocs > /dev/null 2>$ERROR_FILE

        # $? is the status of the last executed program.
        # 0 is success, anything else indicates some kind of error
        if [ "$?"  == "0" ]
        then
            if  [ "$SITE" == "sd" ]
            then
                GOAL="divvun-no"
            else
                GOAL="giellatekno"
            fi
            cd src/
            echo "copying files to tomcat5 dir $GOAL..."
            sudo -u tomcat5 /bin/cp -a * /var/lib/tomcat5/webapps/$GOAL/project/src/.
            if [ "$?"  != "0" ]
            then
                (
                echo "From: borre.gaup@samediggi.no"
                echo "Subject: Error copying files to webapps dir"
                echo "TO:$MAIL_TO"
                echo ""
                )|sendmail -t
            fi
        else
            echo "Sending error mail ..."
            (
            echo "From: borre.gaup@samediggi.no"
            echo "Subject: Error validating files in $SITE"
            echo "TO:$MAIL_TO"
            echo ""
            cat $ERROR_FILE
            )|sendmail -t
        fi
    done
}

fetch_giella_and_divvun
validate_sites

echo "Done updating giellatekno and divvun:-)!"
