#!/bin/bash
# $Id$
# This script is written by Børre Gaup, and is licensed under the
# GPL, version 2 or later.
#
# Shell script for exporting divvun.no and giellaktekno www-pages from cvs 
# to the official www-directory
#
# To get cvs ssh working without password prompting:
# ssh-keygen -t rsa
# <just type enter to all questions>ll
# chmod 0644 .ssh/id_rsa.pub
# scp id_rsa.pub <user>@cochise.uit.no:.ssh/authorized_keys2
FORREST_HOME=$HOME/forrest
PATH=$PATH:$FORREST_HOME/bin
CVS_RSH=ssh
MAIL_FROM="boerre@cochise.uit.no"
MAIL_TO="borre.gaup@samediggi.no"
# This function uses cvs to checkout the directory given as it's argument,
# or updates the given directory.

checkout()
{
    TEMPDIR=$1
    echo "Updating $TEMPDIR ..."
    cd
    if  ! [ -x $TEMPDIR ]; then
            (echo "From: $MAIL_FROM"
            echo "Subject: cvs checkout error"
            echo "TO:$MAIL_TO"
            echo "")|/usr/lib/sendmail -t
            echo "No point in continuing without any data to work on ..."
            exit 1
    else
        cd $TEMPDIR
        cvs -z4 up -dP
        if [ "$?" != "0" ]; then
                echo "cvs up failed in $TEMPDIR ..."
            (echo "From: $MAIL_FROM"
            echo "Subject: cvs update error"
            echo "TO:$MAIL_TO"
            echo "")|/usr/lib/sendmail -t
            exit 1
        fi
        cd doc
        cvs -z4 up -dP
        if [ "$?" != "0" ]; then
                echo "cvs up failed $TEMPDIR/doc ..."
            (echo "From: $MAIL_FROM"
            echo "Subject: cvs update error"
            echo "TO:$MAIL_TO"
            echo "")|/usr/lib/sendmail -t
            exit 1
        fi
        # This doesn't belong to the forrest sources and will cause an error 
        # when building the site
        rm -rf admin/projman/Projects
        cd
    fi
}

# This function uses the 'checkout' function to update or checkout
# the two directories used in the giellatekno and divvun sites.
# It also makes a symbolic link to gt/doc in the gtuit and sd sites, 
# making complete 'forrest-trees' out of both xtdoc/sd and xtdoc/gtuit

fetch_giella_and_divvun()
{
    for CVS_DIR in xtdoc/sd xtdoc/gtuit
    do
        checkout $CVS_DIR
    done

}

# This function validates the documents in the xtdoc/sd and xtdoc/gt 
# directories.
# If successfull it copies the relevant files to the tomcat-servers 
# directories, else it sends an e-mail to the site administrator.

build_and_copy_sites()
{
    for SITE in sd gtuit
    do
        cd $HOME/xtdoc/$SITE

        # Build the site, at the same time checking the docs
        echo "Building $SITE ..."
        forrest -Dforrest.jvmargs=-Djava.awt.headless=true

        # $? is the status of the last executed program.
        # 0 is success, anything else indicates some kind of error
        if [ "$?"  == "0" ]
        then
            cd build/site
            scp -r * $SITE@giellatekno.uit.no:~/public_html/.
            if [ "$?"  != "0" ]
            then
                (
                echo "From: $MAIL_FROM"
                echo "Subject: Error copying files to webapps dir"
                echo "TO:$MAIL_TO"
                echo ""
                )|/usr/lib/sendmail -t
                echo "copying files to $SITE failed..."
            fi
        else
            echo "Sending error mail ..."
            (
            echo "From: $MAIL_FROM"
            echo "Subject: Error validating files in $SITE"
            echo "TO:$MAIL_TO"
            echo ""
            cat $ERROR_FILE
            )|/usr/lib/sendmail -t
        fi
    done
}

fetch_giella_and_divvun
build_and_copy_sites

echo "Done updating giellatekno and divvun:-)!"
