#!/bin/bash

egrep 'java\.lang\.OutOfMemoryError|BUILD FAILED'  $HOME/xtdoc/sd/divvun.log
#test -e .
if [ "$?" == "0" ]; then
	processes=(`ps u | grep sd | grep java | grep -v grep | sed -e 's/^sd *//g'|cut -f1 -d" "`)
	i=0
	last_process=${#processes[*]}
	while [ $i -lt $last_process ]; do
		kill ${processes[$i]}
		echo "$i: ${processes[$i]}"
		let i++
	done
	sleep 30
	while [ $i -lt $last_process ]; do
		kill -9 ${processes[$i]}
		echo "$i: ${processes[$i]}"
		let i++
	done
	cd $HOME/xtdoc/sd
	$HOME/forrest/bin/forrest run -Dforrest.jvmargs=\"-Djava.awt.headless='true' -Dfile.encoding=utf-8\" > $HOME/xtdoc/sd/divvun.log 2>&1 &
fi
