# This is Makefile to build tools
# $Id: Makefile,v 1.2 2001/11/10 15:02:22 antos Exp $ 

CPP = g++
CFLAGS = -ansi -Wall -O2

dic2traskelet: dic2traskelet.C
	$(CPP) $(CFLAGS) -o dic2traskelet dic2traskelet.C

