# A number of useful aliases to run lookup sessions on the langauges we support.

# Sámi languages:
alias   usme='lookup -flags mbTT $GTHOME/gt/sme/bin/sme.fst'
alias   dsme='lookup -flags mbTT $GTHOME/gt/sme/bin/isme.fst'
alias   usmj='lookup -flags mbTT $GTHOME/gt/smj/bin/smj.fst'
alias   dsmj='lookup -flags mbTT $GTHOME/gt/smj/bin/ismj.fst'
alias   usma='lookup -flags mbTT $GTHOME/gt/sma/bin/sma.fst'
alias   dsma='lookup -flags mbTT $GTHOME/gt/sma/bin/isma.fst'
alias   usmn='lookup -flags mbTT $GTHOME/gt/smn/bin/smn.fst'
alias   dsmn='lookup -flags mbTT $GTHOME/gt/smn/bin/ismn.fst'
alias   usms='lookup -flags mbTT $GTHOME/gt/sms/bin/sms.fst'
alias   dsms='lookup -flags mbTT $GTHOME/gt/sms/bin/isms.fst'
alias   usjd='lookup -flags mbTT $GTHOME/gt/sjd/bin/sjd.fst'
alias   dsjd='lookup -flags mbTT $GTHOME/gt/sjd/bin/isjd.fst'
alias   usje='lookup -flags mbTT $GTHOME/gt/sje/bin/sje.fst'
alias   dsje='lookup -flags mbTT $GTHOME/gt/sje/bin/isje.fst'

# Other languages:
alias   udeu='lookup -flags mbTT $GTHOME/st/deu/bin/deu.fst'
alias   ddeu='lookup -flags mbTT $GTHOME/st/deu/bin/ideu.fst'
alias   ufao='lookup -flags mbTT $GTHOME/st/fao/bin/fao.fst'
alias   dfao='lookup -flags mbTT $GTHOME/st/fao/bin/ifao.fst'
alias   ukal='lookup -flags mbTT $GTHOME/st/kal/bin/kal.fst'
alias   dkal='lookup -flags mbTT $GTHOME/st/kal/bin/ikal.fst'
alias   uiku='lookup -flags mbTT $GTHOME/st/iku/bin/iku.fst'
alias   diku='lookup -flags mbTT $GTHOME/st/iku/bin/iiku.fst'
alias   uipk='lookup -flags mbTT $GTHOME/st/ipk/bin/ipk.fst'
alias   dipk='lookup -flags mbTT $GTHOME/st/ipk/bin/iipk.fst'
alias   unob='lookup -flags mbTT $GTHOME/st/nob/bin/nob.fst'
alias   dnob='lookup -flags mbTT $GTHOME/st/nob/bin/inob.fst'
alias   unon='lookup -flags mbTT $GTHOME/st/non/bin/non.fst'
alias   dnon='lookup -flags mbTT $GTHOME/st/non/bin/inon.fst'
alias   unno='lookup -flags mbTT $GTHOME/st/nno/bin/nno.fst'
alias   dnno='lookup -flags mbTT $GTHOME/st/nno/bin/inno.fst'
alias   ucor='lookup -flags mbTT $GTHOME/st/cor/bin/cor.fst'
alias   dcor='lookup -flags mbTT $GTHOME/st/cor/bin/icor.fst'
alias   ueng='lookup -flags mbTT $GTHOME/st/eng/bin/eng.fst'
alias   deng='lookup -flags mbTT $GTHOME/st/eng/bin/ieng.fst'
alias   uces='lookup -flags mbTT $GTHOME/st/ces/bin/ces.fst'
alias   dces='lookup -flags mbTT $GTHOME/st/ces/bin/ices.fst'
alias   uamh='lookup -flags mbTT $GTHOME/st/amh/bin/amh.fst'
alias   damh='lookup -flags mbTT $GTHOME/st/amh/bin/iamh.fst'

# Other FU languages:
alias   ufin='lookup -flags mbTT $GTHOME/kt/fin/bin/fin.fst'
alias   dfin='lookup -flags mbTT $GTHOME/kt/fin/bin/ifin.fst'
alias   ukom='lookup -flags mbTT $GTHOME/kt/kom/bin/kom.fst'
alias   dkom='lookup -flags mbTT $GTHOME/kt/kom/bin/ikom.fst'

# Bilingual transducers:
alias smesmj='lookup -flags mbTT $GTHOME/words/dicts/smesmj/bin/smesmj.fst'
alias smjsme='lookup -flags mbTT $GTHOME/words/dicts/smesmj/bin/smjsme.fst'
alias smenob='lookup -flags mbTT $GTHOME/words/dicts/smenob/bin/smenob.fst'
alias nobsme='lookup -flags mbTT $GTHOME/words/dicts/smenob/bin/ismenob.fst'
alias kaleng='lookup -flags mbTT $GTHOME/words/dicts/kaleng/bin/kaleng.fst'
alias kaldan='lookup -flags mbTT $GTHOME/words/dicts/kaldan/bin/kaldan.fst'
alias kaldic='lookup -flags mbTT $GTHOME/words/dicts/kaldan/bin/kaldic.fst'
alias fkvnob='lookup -flags mbTT $GTHOME/kvensk/bin/fkvnob.fst'
alias nobfkv='lookup -flags mbTT $GTHOME/kvensk/bin/nobfkv.fst'
alias fitswe='lookup -flags mbTT $GTHOME/kvensk/fitswe/bin/fitswe.fst'
alias swefit='lookup -flags mbTT $GTHOME/kvensk/swefit/bin/swefit.fst'

# Other transducers
alias ogeo='lookup -flags mbTT ~/GTHOME/words/dicts/smi/geo/bin/geo.fst'
